#define BASE_PROTECTION_RADIUS 500 // In meters
#define BASE_PROTECTION_HANDLER_TIMEOUT 5 // In seconds

#define TLD_HELI_PILOT_CLASS "B_Helipilot_F"

#define TLD_XIANS [TLD_XIAN_1, TLD_XIAN_2, TLD_XIAN_3, TLD_XIAN_4]
#define TLD_FACTORY_PARTS [TLD_FACTORY_PART_1, TLD_FACTORY_PART_2, TLD_FACTORY_PART_3, TLD_FACTORY_PART_4, TLD_FACTORY_PART_5, TLD_FACTORY_PART_6, nearestBuilding [6213, 16277, 0]]
#define TLD_COMMS [TLD_COMM_1, TLD_COMM_2, TLD_COMM_3, TLD_COMM_4]
#define TLD_VARSUKS [TLD_VARSUK_1, TLD_VARSUK_2, TLD_VARSUK_3, TLD_VARSUK_4]
